[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000
  publish = "build"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200